[project]
name = "market-bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
hello = "market_bench:hello"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
