[project]
name = "predibench-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataset>=1.6.2",
    "fastapi>=0.116.1",
    "huggingface-hub>=0.34.4",
    "pydantic>=2.11.7",
    "uvicorn[standard]>=0.35.0",
]
