name: Scheduled Backend Updates

on:
  schedule:
    - cron: '0 */1 * * *'  # Every hour
  workflow_dispatch:  # Allow manual triggering

concurrency:
  group: scheduled-back-updates
  cancel-in-progress: true

jobs:
  update-backend-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: |
          cd predibench-core
          uv sync

      - name: Update backend cache
        env:
          BUCKET_PREDIBENCH: "predibench-prod"
        run: |
          cd predibench-core
          uv run python scripts/generate_backend_cache.py

      - name: Log completion
        run: |
          echo "Backend cache update completed at $(date)"