name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install dependencies
      run: |
        cd predibench-core
        uv sync
    - name: Run tests
      env:
        BUCKET_PREDIBENCH: "predibench"
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        BRIGHT_SERPER_API_KEY: ${{ secrets.BRIGHT_SERPER_API_KEY }}
        SCRAPE_DO_API_KEY: ${{ secrets.SCRAPE_DO_API_KEY }}
        SCRAPFLY_API_KEY: ${{ secrets.SCRAPFLY_API_KEY }}
      run: |
        cd predibench-core && uv run python -m pytest tests/